name: transnode
version: 0.0.1
description: A transnode web application
dependencies:
  angular: any
  angular_ui: any
  browser: any
  unittest: any
  ctrl_alt_foo: any
dev_dependencies:
    dartmocks: ">= 0.5.0"
